### ISSUE TITLE
Type tinyint fails validation and doesn't load when the value is > 128

### ISSUE THREAD

**Issue by wndprc** [wintersrd/pipelinewise-tap-mssql#2]
On SQL Server tynyint is defined as 0 to 255. I'm getting an error when loading tinyints > 127 because the code is setting             "minimum": -128, "maximum": 127,

**Comment by s7clarke10** [comment]
Thank you for bring this to our attention. Resolved by PR : https://github.com/wintersrd/pipelinewise-tap-mssql/pull/54
