### ISSUE TITLE
Why defaulting to TSD "8.0", it doesn't work correctly and should be "7.3"?

### ISSUE THREAD

**Issue by s7clarke10** [wintersrd/pipelinewise-tap-mssql#23]
@dgoo2308, in the pull request (https://github.com/wintersrd/pipelinewise-tap-mssql/pull/14), there was a change in the connection.py script in it there is a default parameter for TDS to be 8.0?

https://github.com/wintersrd/pipelinewise-tap-mssql/blob/7710d19b47940ce3396630b772187b7571d2ef82/tap_mssql/connection.py#L39

I have noted with this version 8.0 that old issues with pymssql of dates being emitted as strings rather than a datetime.date are reintroduced.

I believe based on this documentation https://pymssql.readthedocs.io/en/stable/faq.html?highlight=date-time#pymssql-does-not-unserialize-date-and-time-columns-to-datetime-date-and-datetime-time-instances and here http://www.freetds.org/faq.html#Does.FreeTDS.support.Microsoft.servers , that we should have a default version of 7.3.

When I manually pass in a config item "tds_version": "7.3", the SQL Server datatypes date and time are being converted to the correct Python datatypes.

I'm proposing that the default should therefore be 7.3 but wanted to have a better understanding of why version 8.0 was picked. Maybe this is because the naming conventions between SQL Server and FreeTDS is different - http://www.freetds.org/userguide/tdshistory.html. I believe pymssql bundles FreeTDS and 7.3 is the highest supported version?

**Comment by dgoo2308** [comment]
@s7clarke10 there was no default version defined in the tap-mssql which reverted to the FreeTDS internal default..
 
I choose 8.0 as that worked for me, I'm neutral on this, I choose a higher version since the default internal FreeTDS version was not working for me on some versions of MSSQL.

Which is why I added the option to be able to choose a version, while defaulting to 8.0. 

If using 7.3 would be more preferable as the default version, please open a pull request.

**Comment by s7clarke10** [comment]
Thanks so much for answering my enquiry re TDS. I have opened a pull request that introduces log based replication, change data capture and additional data types.

As part of this I set the default to TDS to 7.3 to supports native date / time data types. My testing shows that 7.3 should support higher versions of SQL Server including AWS RDS versions of SQL Server.

Thank you for introducing the feature to select versions of TDS I know it will be helpful to users of this tap.

Cheers
Steve

**Comment by dgoo2308** [comment]
@s7clarke10 can you then close this issue?

**Comment by s7clarke10** [comment]
Thanks for answering the question. I have looked into the somewhat confusing order of TDS versions and also reviewed the pymssql code.

It appears that 7.3 is the latest supported version so this is the default in the new release and that is the new default in the PR which was released to MAIN recently.

Thanks again for your support and making a configurable option for TDS version.
