### ISSUE TITLE
Add support for APS/PDW/Azure Synapse Dedicated SQL Pool

### ISSUE THREAD

**Issue by cwegener** [wintersrd/pipelinewise-tap-mssql#28]
With Microsoft's APS/PDW technology being made available to the masses in an affordable manner via Azure Synapse Dedicated SQL Pool, does it make sense to support this system as a source?

All that is needed to support PDW is:

- Handle the current `select @@lock_timeout` behaviour in the `log_server_params()` method. `lock_timeout` is only available from `sys.dm_pdw_nodes_exec_sessions` in PDW and access to that DMV in PDW requires elevated permissions (VIEW SERVERSTATE).

- Add support for supplying `conn_properties` to pymssql in order to override the built-in session properties supplied by pymssql by default, because one of the default settings (`CURSOR_CLOSE_ON_COMMIT`) is not available on PDW.

**Comment by s7clarke10** [comment]
@cwegener , sorry it has taken so long to makes this change. I am interested in your thoughts on this PR. I believe it implements your excellent suggestion.

**Comment by cwegener** [comment]
Hi Steve,

I just ran a quick test from the new branch in #79 and the `conn_properties` works exactly as intended!

Thanks for implementing this!
