### ISSUE TITLE
Inquiry regarding tap readiness for production usage

### ISSUE THREAD

**Issue by aaronsteers** [wintersrd/pipelinewise-tap-mssql#3]
Hello, @wintersrd! I have been looking for a python-based replacement for the https://github.com/singer-io/tap-mssql tap which is based on clojure (java-based). Is this tap working well in production scenarios and would it be okay for our team to create a dependency on it?

Update:
 - This topic is getting some attention lately 😄:
    - https://www.reddit.com/r/dataengineering/comments/l863az/meltano_elt_for_the_devops_era_open_source/gld9da1?utm_source=share&utm_medium=web2x&context=3
    - https://gitlab.com/meltano/meltano/-/issues/1175#note_500873947

**Comment by wintersrd** [comment]
@aaronsteers clearly I don't pay much attention here. This tap was built to address specific needs for our company, but I can say that we have run it for more than two years in production with no significant issues

**Comment by aaronsteers** [comment]
Thanks, @wintersrd - I think we've chatted at least a few times since I originally posted this. But clearly the community is excited to use this - thanks again. 🙌
