### ISSUE TITLE
SQL Server with Case Sensitive Collation Error

### ISSUE THREAD

**Issue by dantwi-cuda** [wintersrd/pipelinewise-tap-mssql#34]
Hi @wintersrd 
Thank you for all the great work you've done on this project. I'm using this tap and noticed that all views under INFORMATION_SCHEMA.[TABLES, COLUMNS, CONSTRAINSTS] in SQL Server are are not working when  SQL Server is set to case sensitive collation. This is because all column names and view names under INFORMATION_SCHEMA in SQL Server are Upper case by default. Which means the following line           
```
  """SELECT table_schema,
                table_name,
                table_type
            FROM INFORMATION_SCHEMA.tables c" 
```
and other instances of Queries on the INFORMATION_SCHEMA view in __INIT__.py will always error out when SQL Server collation is case sensitive. I believe the fix might be to change "tables" in the query above to "TABLES" so that it works irrespective of the collation. There are other queries as well which will need the view name and column names to also change to upper case. Attached is the modified __INIT__.py file
[__init__.txt](https://github.com/wintersrd/pipelinewise-tap-mssql/files/10370111/__init__.txt)

**Comment by wesseljt** [comment]
@dantwi-cuda  I experienced this issue as well. Could you submit a PR here?
