### ISSUE TITLE
pip distribution unavailable

### ISSUE THREAD

**Issue by flypenguin** [wintersrd/pipelinewise-tap-mssql#4]
if I execute `pip install pipelinewise-tap-mssql` I get this error message:

```
ERROR: Could not find a version that satisfies the requirement pipelinewise-tap-mssql (from versions: none)
ERROR: No matching distribution found for pipelinewise-tap-mssql
```

pypi.org also does not know the package name. I'd say this is a bug, and it also prevents me from including this tap into meltano.

**Comment by momomoro** [comment]
I'm also facing this same issue.  I was able to install the package just fine about a week ago though.  Currently I have to checkout this package and run setup.py install

**Comment by prae04** [comment]
bumping this issue to increase adoption for this wonderful tap!

**Comment by divv** [comment]
Yes, it looks like the `README.md` retains some boilerplate from another repo and that this lib has not been properly submitted to PyPi.

I have been able to use this tap in Meltano by specifying the github url for the `pip_url` parameter. Ditto you can `pip install <github-url>` as well. But it would be very nice if this was in PyPi properly.

@wintersrd

**Comment by James-DBA-Anderson** [comment]
For anyone else hitting this issue, I had to remove all trace of tap-mssql from my meltano.yml before installing via pip_url would work.

I kept getting the following before removing the broken settings:

```
ERROR: Could not find a version that satisfies the requirement tap-mssql (from versions: none)
ERROR: No matching distribution found for tap-mssql
```

I'm using the settings described here https://gitlab.com/vischous/oracle2mssql/-/blob/master/oracle2mssql/meltano.yml

I am new to Meltano so I could also have been doing something stupid.

**Comment by wintersrd** [comment]
This is now on pypi, with all proposed changes
