### ISSUE TITLE
Columns of type `datetimeoffset` are omitted during extraction

### ISSUE THREAD

**Issue by edgarrmondragon** [wintersrd/pipelinewise-tap-mssql#50]
Reporting here in lieu of a user of this tap.

It seems this tap omits columns in the source db with type `datetimeoffset`, even though they are selected for extraction.

Links:

* https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-ver16

**Comment by s7clarke10** [comment]
Hi @edgarrmondragon , thanks for letting us know about that. I do know that datetimeoffset is a datatype that was introduced by Microsoft in more recent times. Will need to check if the underlying pymssql supports this datatype and if so cater for this correctly. Most like we can add this as a supported field.

I have another issue raised with me that is not handling a datetime, which is set to `9999-12-31 23:59:59.9999999`. I will look to fix this issue at the same time and possibly the issue : https://github.com/wintersrd/pipelinewise-tap-mssql/issues/2.

I won't be in a position to look at this until next week.

**Comment by s7clarke10** [comment]
Resolved by PR : https://github.com/wintersrd/pipelinewise-tap-mssql/pull/54. @edgarrmondragon , can you let the appropriate person know that the `Datetimeoffset` is now supported. Thanks
