### ISSUE TITLE
Error in casting of datetimeoffset?

### ISSUE THREAD

**Issue by MarenElise** [wintersrd/pipelinewise-tap-mssql#58]
https://github.com/wintersrd/pipelinewise-tap-mssql/blob/f5bc24abdde3ee7bb73aafeecd438188b427e855/tap_mssql/sync_strategies/common.py#L129

Should this line be `CONVERT(VARCHAR,{column_name},127)` instead of `CONVERT(VARCHAR,dt_offset_col,127)`

I am getting this error: 
Plugin configuration is invalid
pymssql._pymssql.ProgrammingError: (207, b"Invalid column name 'dt_offset_col'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

**Comment by s7clarke10** [comment]
Hi @MarenElise I have prepared a PR for resolving this issue.

Are you able to verify that the change prepared in this branch resolves the issue?

https://github.com/s7clarke10/pipelinewise-tap-mssql/tree/bug/fix_column_formatting

**Comment by cameronSMN** [comment]
@MarenElise Thanks for reporting this.  I came across the this bug last week and resolved it in the same way.

@s7clarke10 I have tested your change in https://github.com/s7clarke10/pipelinewise-tap-mssql/tree/bug/fix_column_formatting and I confirm that it resolves the issue.
