### ISSUE TITLE
Schema is not retaining the correct column order

### ISSUE THREAD

**Issue by s7clarke10** [wintersrd/pipelinewise-tap-mssql#62]
The tap has logic to order the columns based the SQL order clause issued to the database catalog tables. You can see this in the following block of code.

https://github.com/wintersrd/pipelinewise-tap-mssql/blob/8028e65b51c2ebb750e8f240aee5a9bd6c46f8ea/tap_mssql/__init__.py#L233-L261

Correct Column Order.

![image](https://github.com/wintersrd/pipelinewise-tap-mssql/assets/84364906/0311202d-b806-44f3-9cdd-8106f8d4c279)

Result in Snowflake our variant of Target Snowflake (which respects ordered columns).

![image](https://github.com/wintersrd/pipelinewise-tap-mssql/assets/84364906/27803613-866f-4dab-b9bc-c1f74b12df23)

It is a different order!

I suspect there is something in the code https://github.com/wintersrd/pipelinewise-tap-mssql/blob/8028e65b51c2ebb750e8f240aee5a9bd6c46f8ea/tap_mssql/__init__.py#L274-L275 which may be converting the ordered column into an unordered List. Need to look at a code change which will respect the ordered columns returned by the SQL Server query.

**Comment by mjsqu** [comment]
After some investigation, the itertools doesn't appear to be scrambling the column ordering. The columns are correctly ordered at this point, but they lose their ordering when they are selected from the catalog. The `desired_columns` function may be the source of the problem. Throwing a few `LOGGER` statements in here shows:

https://github.com/wintersrd/pipelinewise-tap-mssql/blob/8028e65b51c2ebb750e8f240aee5a9bd6c46f8ea/tap_mssql/__init__.py#L408-L417


```
INFO discovered_table.schema.properties.keys()=dict_keys(['AddressID', 'IsDeleted', 'AddressLine1', 'AddressLine2', 'City', 'Confidential', 'PostCode', 'State', 'Suburb', 'GeoCodeInfoID', 'CountryID', 'CreatedBy', 'CreatedDateTime', 'ModifiedBy', 'ModifiedDateTime'])

INFO selected={'City', 'Suburb', 'Confidential', 'State', 'CountryID', 'ModifiedBy', 'PostCode', 'ModifiedDateTime', 'GeoCodeInfoID', 'CreatedBy', 'CreatedDateTime', 'AddressLine2', 'AddressID', 'IsDeleted', 'AddressLine1'}

INFO columns={'City', 'Suburb', 'Confidential', 'State', 'CountryID', 'ModifiedBy', 'PostCode', 'ModifiedDateTime', 'GeoCodeInfoID', 'CreatedBy', 'CreatedDateTime', 'AddressLine2', 'AddressID', 'IsDeleted', 'AddressLine1'}
```

The `selected` set appears to be coming back in a strange order.
