### ISSUE TITLE
Add ntext type to STRING_TYPES

### ISSUE THREAD

**Issue by HaydenNess** [wintersrd/pipelinewise-tap-mssql#91]
Columns of "ntext" type are not currently synced.  

Adding "ntext" to STRING_TYPES appears to fix the issue for me.

**Comment by s7clarke10** [comment]
Would you like to submit a PR for this? It would help the whole community.CheersSteveOn 17 Oct 2024, at 6:39 PM, Hayden Ness ***@***.***> wrote:﻿
Columns of "ntext" type are not currently synced.
Adding "ntext" to STRING_TYPES appears to fix the issue for me.

**Comment by s7clarke10** [comment]
Resolved by #96
