### ISSUE TITLE
LOG_BASED replication issues single null record when on changes

### ISSUE THREAD

**Issue by chadcampling-opteon** [wintersrd/pipelinewise-tap-mssql#93]
Hi,

I'm currently trying to get CDC log based replication working from SQL Server to Snowflake. I'm using this tap for my loader with Meltano and I'm encountering an issue with the Log based sync when there are no changes on my test table. What I'm seeing is a single record produced after the schema and the record containing all null values. This then chokes the snowflake target as the primary ley value for the tale is null.

Is this NULL record intended as I couldn't find anything in the singer spec on it although this is all somewhat new to me? In the case of there being no data to sync since last extract what are the expected messages to be produced by the tap?

``` json
{
    "type": "RECORD",
    "stream": "locality-Suburb",
    "record": {
        "SuburbId": null,
        "StateId": null,
        "PostcodeName": null,
        "RegexPostcodeName": null,
        "Name": null,
        "RegexName": null,
        "IsActive": null,
        "LGA": null,
        "DateConfirmed": null,
        "ConfirmerId": null,
        "MunicipalityId": null,
        "Town": null,
        "SchedulingRegionId": null,
        "SchedulingRegionName": null,
        "RPDataLocationId": null,
        "_sdc_operation_type": null,
        "_sdc_lsn_commit_timestamp": null,
        "_sdc_lsn_deleted_at": null,
        "_sdc_lsn_value": null,
        "_sdc_lsn_seq_value": null,
        "_sdc_lsn_operation": null
    },
    "version": 1729457923663,
    "time_extracted": "2024-10-20T20:58:43.752838Z"
}
```

**Comment by mjsqu** [comment]
Hello @chadcampling-opteon - please could you review the following Q&A I wrote regarding a similar issue:
https://stackoverflow.com/questions/78719075/sql-server-cdc-cdc-fn-cdc-get-all-changes-returns-a-row-containing-all-null-va/78719076#78719076

I don't recall in a lot of detail but it was something like the identity role that initially set up CDC was not the same as the role querying via CDC

**Comment by chadcampling-opteon** [comment]
@mjsqu Thanks so much for the prompt response, this was exactly the issue and none of my search had turned up anything. Confirmed pipeline is working correctly now.
